language: go
go: 1.9
sudo: required
services: docker

before_install:
  - go get -u github.com/codegangsta/negroni
  - go get -u github.com/gorilla/mux
  - go get -u github.com/unrolled/render
  - go get -u github.com/spf13/pflag

install:
  # docker build: --rm remove the middle container, -t names the image as name:tag or name.
  # liuyh73/go-web-form is the image name
  - docker build --rm -t liuyh73/go-web-form .
  # docker run: create a container called go-web-form to run the image (liuyh73/go-web-form).
  # the former go-web-form is the container name, the latter liuyh73/go-web-form is the image name 
  - docker run -d -p 127.0.0.1:8080:8080 --name go-web-form liuyh73/go-web-form

script:
  - docker ps | grep -q go-web-form

